{
 "title": "Spotify stats",
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  { "title": "Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Time spent streaming",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with tracks as\r\n    (select distinct on (ss.track_uri) ss.track_uri, owr.id\r\n      from spotify_streams ss\r\n      join musicbrainz_recordings mr on mr.spotify_uri = ss.track_uri\r\n      join owned_recordings owr on owr.recording_id = mr.musicbrainz_id),\r\n  complete_albums as\r\n    (select name, album_id, album_type, total_tracks from\r\n      (select name, album_id, album_type, total_tracks, count(*) as tracks\r\n        from\r\n          (select distinct on (track_uri) name, album_id, total_tracks, album_type\r\n            from spotify_streams ss\r\n            join spotify_tracks st on st.spotify_uri = ss.track_uri\r\n            join spotify_albums sa on sa.spotify_id = st.album_id\r\n            where $__timeFilter(timestamp) and reason_end = 'trackdone')\r\n        group by album_id, name, album_type, total_tracks)\r\n      where tracks = total_tracks\r\n      order by total_tracks desc)\r\n  select sum(ms_played) \"Total\",\r\n      sum(ms_played) filter (where reason_end = 'trackdone') as \"Completed\",\r\n      sum(ms_played) filter (where tracks.id is not null) as \"Owned tracks\",\r\n      sum(ms_played) filter (where tracks.id is null and reason_end = 'trackdone') as \"Unowned tracks (completed)\",\r\n      sum(ms_played) filter (where ca.album_id is not null) as \"Complete albums, singles and compilations\",\r\n      avg(ms_played) as \"Average stream length\",\r\n      avg(ms_played) filter (where reason_end = 'trackdone') as \"Average complete stream length\",\r\n      avg(ms_played) filter (where skipped = true\r\n        or reason_end in ('backbtn', 'unknown', 'endplay', 'fwdbtn')) as \"Mean time before skip\"\r\n    from spotify_streams ss\r\n    join spotify_tracks st on st.spotify_uri = ss.track_uri\r\n    left join tracks on ss.track_uri = tracks.track_uri\r\n    left join complete_albums ca on ca.album_id = st.album_id\r\n    where $__timeFilter(timestamp);"
    },
    { "rawSql": "\r\n" }
   ]
  },
  {
   "title": "Time streamed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "with tracks as\r\n  (select distinct on (ss.track_uri) ss.track_uri, owr.id \r\n    from spotify_streams ss\r\n    join musicbrainz_recordings mr on mr.spotify_uri = ss.track_uri\r\n    join owned_recordings owr on owr.recording_id = mr.musicbrainz_id)\r\n  select $__timeGroupAlias(timestamp, $__interval),\r\n    sum(ms_played) as \"all tracks\",\r\n    sum(ms_played) filter (where tracks.id is not null) as \"owned tracks\", \r\n    sum(ms_played) filter (where tracks.id is null) as \"unowned tracks\"\r\n  from spotify_streams ss\r\n  left join tracks on ss.track_uri = tracks.track_uri\r\n  where $__timeFilter(timestamp)\r\n  group by time"
    }
   ]
  },
  {
   "title": "Time played per track",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "select sum(ms_played), track_uri from spotify_streams where $__timeFilter(timestamp) group by track_uri ORDER BY sum DESC"
    }
   ]
  },
  {
   "title": "Time streamed per hour of the week",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "select sum, label\r\n  from (\r\n    SELECT\r\n        extract(isodow from timestamp) as day,\r\n        extract(hour from timestamp) as hour,\r\n        to_char(timestamp, 'Day HH24:00') as label,\r\n        sum(ms_played) as sum\r\n      FROM spotify_streams\r\n      WHERE $__timeFilter(timestamp)\r\n      GROUP BY label, day, hour\r\n      ORDER BY day, hour\r\n  )"
    }
   ]
  },
  { "title": "Streams", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Counts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \r\n    count(distinct ss.track_uri) \"Tracks\",\r\n    count(distinct album_id) \"Albums\",\r\n    count(distinct artist_id) \"Artists\"\r\n  from spotify_streams ss\r\n  join spotify_tracks st on ss.track_uri = st.spotify_uri\r\n  join spotify_albums sa on st.album_id = sa.spotify_id\r\n  join spotify_track_artists sta on sta.track_id = st.spotify_id\r\n  where $__timeFilter(timestamp);"
    }
   ]
  },
  {
   "title": "Counts from complete streams",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with tracks as\r\n  (select distinct on (ss.track_uri) ss.track_uri, owr.id\r\n    from spotify_streams ss\r\n    join musicbrainz_recordings mr on mr.spotify_uri = ss.track_uri\r\n    join owned_recordings owr on owr.recording_id = mr.musicbrainz_id)\r\n  select \r\n      count(distinct ss.track_uri) \"Tracks\",\r\n      count(distinct ss.track_uri) filter (where tracks.id is null) \"Unowned Tracks\",\r\n      count(distinct album_id) \"Albums\",\r\n      count(distinct artist_id) \"Artists\"\r\n    from spotify_streams ss\r\n    join spotify_tracks st on ss.track_uri = st.spotify_uri\r\n    join spotify_albums sa on st.album_id = sa.spotify_id\r\n    join spotify_track_artists sta on sta.track_id = st.spotify_id\r\n    left join tracks on ss.track_uri = tracks.track_uri\r\n    where $__timeFilter(timestamp) and reason_end <> 'trackdone'"
    }
   ]
  },
  {
   "title": "Stream counts",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with tracks as\r\n  (select distinct on (ss.track_uri) ss.track_uri, owr.id\r\n    from spotify_streams ss\r\n    join musicbrainz_recordings mr on mr.spotify_uri = ss.track_uri\r\n    join owned_recordings owr on owr.recording_id = mr.musicbrainz_id)\r\n  select count(*) as \"Streams\",\r\n    count(*) filter (where reason_end = 'trackdone') as \"Completed streams\",\r\n    count(*) filter (where tracks.id is not null) as \"Owned track streams\",    \r\n    count(*) filter (where tracks.id is null) as \"Unowned track streams\",\r\n    count(*) filter (where tracks.id is null and reason_end = 'trackdone') as \"Unowned track completed streams\"\r\n  from spotify_streams ss\r\n  left join tracks on ss.track_uri = tracks.track_uri\r\n  where $__timeFilter(timestamp);"
    }
   ]
  },
  {
   "title": "Streams per platform",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "rawSql": "select count(*) as value, platform as metric, $__timeGroupAlias(timestamp, $__interval, 0)\r\n  from spotify_streams where $__timeFilter(timestamp)\r\n  group by time, platform\r\n  order by time"
    }
   ]
  },
  {
   "title": "Stream end reasons",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "select $__timeGroupAlias(timestamp, $__interval), reason_end as metric, count(*)\r\n  from spotify_streams where $__timeFilter(timestamp)\r\n    and reason_end not in ('', 'appload', 'clickrow', 'playbtn', 'popup', 'uriopen', 'unknown')\r\n  group by time, reason_end\r\n  order by time;"
    }
   ]
  },
  {
   "title": "Streams per album type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "rawSql": "select album_type, count(*), $__timeGroupAlias(timestamp, $__interval, 0)\r\n  from spotify_streams ss\r\n  join spotify_tracks st on ss.track_uri = st.spotify_uri\r\n  join spotify_albums sa on st.album_id = sa.spotify_id\r\n  where $__timeFilter(timestamp)\r\n  group by time, album_type\r\n  order by time;"
    }
   ]
  },
  { "title": "Tracks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Tracks needed to cover percentages of total streaming time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) filter (where percent_total_stream_duration <= 0.5) as \"50%\",\r\n    count(*) filter (where percent_total_stream_duration <= 0.75) as \"75%\",\r\n    count(*) filter (where percent_total_stream_duration <= 0.80) as \"80%\",\r\n    count(*) filter (where percent_total_stream_duration <= 0.90) as \"90%\",\r\n    count(*) filter (where percent_total_stream_duration <= 0.95) as \"95%\",\r\n    count(*) filter (where percent_total_stream_duration <= 0.99) as \"99%\"\r\n  from\r\n    (select sum(track_played_sum) over (order by track_played_sum desc) /\r\n        (select sum(ms_played) from spotify_streams) as percent_total_stream_duration\r\n      from\r\n        (select sum(ms_played) as track_played_sum\r\n          from spotify_streams where $__timeFilter(timestamp)\r\n          group by track_uri))"
    }
   ]
  },
  {
   "title": "Complete listen counts for owned tracks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with tracks as\r\n  (select distinct on (ss.track_uri) ss.track_uri, owr.id\r\n    from spotify_streams ss\r\n    join musicbrainz_recordings mr on mr.spotify_uri = ss.track_uri\r\n    join owned_recordings owr on owr.recording_id = mr.musicbrainz_id)\r\n  select sum(c) as \"Total\",\r\n      avg(c) as \"Mean\",\r\n      percentile_cont(0.5) within group (order by c) as \"Median\",\r\n      mode() within group (order by c) as \"Mode\"\r\n    from\r\n      (select ss.track_uri, count(*) as c from spotify_streams ss\r\n        join tracks on ss.track_uri = tracks.track_uri\r\n        where $__timeFilter(timestamp) and reason_end = 'trackdone'\r\n        group by ss.track_uri)"
    }
   ]
  },
  {
   "title": "Top 10 most completely streamed tracks",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "rawSql": "select count(*) filter (where reason_end = 'trackdone') as \"Complete streams\", \r\n    count(*) filter (where reason_end <> 'trackdone') as \"Incomplete streams\",\r\n    track_name,\r\n    track_uri\r\n  from spotify_streams\r\n  where $__timeFilter(timestamp) \r\n  group by track_uri, track_name\r\n  ORDER BY \"Complete streams\" DESC, \"Incomplete streams\" DESC\r\n  LIMIT 10"
    }
   ]
  },
  {
   "title": "Complete listen counts for unowned tracks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with tracks as\r\n  (select distinct on (ss.track_uri) ss.track_uri, owr.id\r\n    from spotify_streams ss\r\n    join musicbrainz_recordings mr on mr.spotify_uri = ss.track_uri\r\n    join owned_recordings owr on owr.recording_id = mr.musicbrainz_id)\r\n  select sum(c) as \"Total\",\r\n      avg(c) as \"Mean\",\r\n      percentile_cont(0.5) within group (order by c) as \"Median\",\r\n      mode() within group (order by c) as \"Mode\"\r\n    from\r\n      (select ss.track_uri, count(*) as c from spotify_streams ss\r\n        left join tracks on ss.track_uri = tracks.track_uri\r\n        where $__timeFilter(timestamp) and reason_end = 'trackdone' and tracks.id is null\r\n        group by ss.track_uri)"
    }
   ]
  },
  {
   "title": "Most completely-streamed unowned tracks",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "rawSql": "with tracks as\r\n  (select distinct on (ss.track_uri) ss.track_uri, owr.id\r\n    from spotify_streams ss\r\n    join musicbrainz_recordings mr on mr.spotify_uri = ss.track_uri\r\n    join owned_recordings owr on owr.recording_id = mr.musicbrainz_id)\r\n  select count(*) filter (where reason_end = 'trackdone') as \"Complete streams\",\r\n    count(*) filter (where reason_end <> 'trackdone') as \"Incomplete streams\",\r\n    track_name\r\n    from spotify_streams ss\r\n    left join tracks on ss.track_uri = tracks.track_uri\r\n    where $__timeFilter(timestamp) and tracks.id is null\r\n    group by ss.track_uri, track_name\r\n  order by \"Complete streams\" desc, \"Incomplete streams\" desc\r\n    limit 20;"
    }
   ]
  },
  {
   "title": "Top 10 most skipped tracks",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "rawSql": "select count(*) filter (where skipped = true\r\n      or reason_end in ('backbtn', 'unknown', 'endplay', 'fwdbtn')) as \"Skipped streams\",\r\n    count(*) filter (where reason_end = 'trackdone') as \"Complete streams\",\r\n    track_name,\r\n    track_uri\r\n  from spotify_streams where $__timeFilter(timestamp)\r\n  group by track_uri, track_name\r\n  order by \"Skipped streams\" desc, \"Complete streams\" desc\r\n  limit 10;"
    }
   ]
  },
  {
   "title": "Streams per track",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "rawSql": "select count(*) as \"Streams\", \r\n    count(*) filter (where reason_end = 'trackdone') as \"Complete streams\", \r\n    track_name,\r\n    track_uri\r\n  from spotify_streams\r\n  where $__timeFilter(timestamp) \r\n  group by track_uri, track_name \r\n  ORDER BY \"Streams\" DESC, \"Complete streams\" DESC"
    }
   ]
  },
  {
   "title": "Top 5 tracks",
   "type": "timeseries",
   "description": "By completely streamed count.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "rawSql": "with metrics as\r\n  (select $__timeGroup(timestamp, $__interval) as time,\r\n      track_name as metric,\r\n      track_uri,\r\n      count(*) as total,\r\n      dense_rank() over (partition by $__timeGroup(timestamp, $__interval) order by count(*) desc) as rank\r\n    from spotify_streams where $__timeFilter(timestamp) and reason_end = 'trackdone'\r\n    group by time, track_uri, metric\r\n    order by time asc, total desc)\r\n  select time, metric, total from metrics where rank <= 5\r\n  union all\r\n  select time, 'Others', sum(total) from metrics where rank > 5\r\n    group by time\r\n    order by time asc;"
    }
   ]
  },
  {
   "title": "Track popularity by time played",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "targets": [
    {
     "rawSql": "select popularity::text, sum(ms_played) as value\r\n  from spotify_streams ss\r\n  join spotify_tracks st on ss.track_uri = st.spotify_uri\r\n  where $__timeFilter(timestamp)\r\n  group by popularity\r\n  order by popularity::integer asc;"
    }
   ]
  },
  {
   "title": "Complete streams per track",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "targets": [
    {
     "rawSql": "select count(*) as \"Streams\", \r\n    count(*) filter (where reason_end = 'trackdone') as \"Complete streams\", \r\n    track_name,\r\n    track_uri\r\n  from spotify_streams\r\n  where $__timeFilter(timestamp) \r\n  group by track_uri, track_name \r\n  ORDER BY \"Complete streams\" DESC, \"Streams\" DESC"
    }
   ]
  },
  { "title": "Artists & Albums", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "Complete album listens by type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with complete_albums as\r\n  (select name, album_id, album_type, total_tracks from\r\n    (select name, album_id, album_type, total_tracks, count(*) as tracks\r\n      from\r\n        (select distinct on (track_uri) name, album_id, total_tracks, album_type\r\n          from spotify_streams ss\r\n          join spotify_tracks st on st.spotify_uri = ss.track_uri\r\n          join spotify_albums sa on sa.spotify_id = st.album_id\r\n          where $__timeFilter(timestamp) and reason_end = 'trackdone')\r\n      group by album_id, name, album_type, total_tracks)\r\n    where tracks = total_tracks\r\n    order by total_tracks desc)\r\n  select album_type, count(*)\r\n    from complete_albums\r\n    group by album_type;"
    }
   ]
  },
  {
   "title": "Top 10 albums",
   "type": "barchart",
   "description": "By completely-streamed track count.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "targets": [
    {
     "rawSql": "select count(*) filter (where reason_end = 'trackdone') as \"Complete streams\",\r\n    count(*) filter (where reason_end <> 'trackdone') as \"Incomplete streams\",\r\n    sa.name\r\n  from spotify_streams ss\r\n  join spotify_tracks st on ss.track_uri = st.spotify_uri\r\n  join spotify_albums sa on sa.spotify_id = st.album_id\r\n  where $__timeFilter(timestamp)\r\n  group by sa.spotify_id, sa.name\r\n  order by \"Complete streams\" desc\r\n  limit 10;"
    }
   ]
  },
  {
   "title": "Top 10 most streamed artists",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "targets": [
    {
     "rawSql": "select count(*) filter (where reason_end = 'trackdone') as \"Complete streams\",\r\n    count(*) filter (where reason_end <> 'trackdone') as \"Incomplete streams\",\r\n    sa.name\r\n  from spotify_streams ss\r\n  join spotify_tracks st on ss.track_uri = st.spotify_uri\r\n  join spotify_track_artists sta on sta.track_id = st.spotify_id\r\n  join spotify_artists sa on sa.spotify_id = sta.artist_id\r\n  where $__timeFilter(timestamp)\r\n  group by sa.spotify_id, sa.name\r\n  order by \"Complete streams\" desc\r\n  limit 10;"
    }
   ]
  },
  {
   "title": "Top 20 unowned albums",
   "type": "barchart",
   "description": "By completely-streamed track count.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
   "targets": [
    {
     "rawSql": "with tracks as\r\n  (select distinct on (ss.track_uri) ss.track_uri, owr.id\r\n    from spotify_streams ss\r\n    join musicbrainz_recordings mr on mr.spotify_uri = ss.track_uri\r\n    join owned_recordings owr on owr.recording_id = mr.musicbrainz_id)\r\n  select count(*) filter (where reason_end = 'trackdone') as \"Complete streams\",\r\n      count(*) filter (where reason_end <> 'trackdone') as \"Incomplete streams\",\r\n      sa.name\r\n    from spotify_streams ss\r\n    join spotify_tracks st on ss.track_uri = st.spotify_uri\r\n    join spotify_albums sa on sa.spotify_id = st.album_id\r\n    left join tracks on ss.track_uri = tracks.track_uri\r\n    where $__timeFilter(timestamp) and tracks.id is null\r\n    group by sa.spotify_id, sa.name\r\n    order by \"Complete streams\" desc\r\n    limit 20;"
    }
   ]
  },
  {
   "title": "Top 5 albums",
   "type": "timeseries",
   "description": "By count of completely streamed tracks.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
   "targets": [
    {
     "rawSql": "with metrics as\r\n  (select $__timeGroup(timestamp, $__interval) as time,\r\n      sa.name as metric,\r\n      count(*) as total,\r\n      dense_rank() over (partition by $__timeGroup(timestamp, $__interval) order by count(*) desc) as rank\r\n    from spotify_streams ss\r\n    join spotify_tracks st on ss.track_uri = st.spotify_uri\r\n    join spotify_albums sa on sa.spotify_id = st.album_id\r\n    where $__timeFilter(timestamp) and reason_end = 'trackdone'\r\n    group by time, sa.spotify_id, metric\r\n    order by time asc, total desc)\r\n  select time, metric, total from metrics where rank <= 5\r\n  union all\r\n  select time, 'Others', sum(total) from metrics where rank > 5\r\n    group by time\r\n    order by time asc;"
    }
   ]
  },
  {
   "title": "Top 5 artists",
   "type": "timeseries",
   "description": "By count of completely streamed tracks.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
   "targets": [
    {
     "rawSql": "with metrics as\r\n  (select $__timeGroup(timestamp, $__interval) as time,\r\n      sa.name as metric,\r\n      count(*) as total,\r\n      dense_rank() over (partition by $__timeGroup(timestamp, $__interval) order by count(*) desc) as rank\r\n    from spotify_streams ss\r\n    join spotify_tracks st on ss.track_uri = st.spotify_uri\r\n    join spotify_track_artists sta on sta.track_id = st.spotify_id\r\n    join spotify_artists sa on sa.spotify_id = sta.artist_id\r\n    where $__timeFilter(timestamp) and reason_end = 'trackdone'\r\n    group by time, sa.spotify_id, metric\r\n    order by time asc, total desc)\r\n  select time, metric, total from metrics where rank <= 5\r\n  union all\r\n  select time, 'Others', sum(total) from metrics where rank > 5\r\n    group by time\r\n    order by time asc;"
    }
   ]
  },
  { "title": "Tags", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 } },
  {
   "title": "Top 5 non-genre tags",
   "type": "timeseries",
   "description": "By count of completely streamed tracks.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
   "targets": [
    {
     "rawSql": "with metrics as\r\n  (select $__timeGroup(timestamp, $__interval) as time,\r\n      name as metric,\r\n      count(*) as total,\r\n      dense_rank() over (partition by $__timeGroup(timestamp, $__interval) order by count(*) desc) as rank\r\n    from spotify_streams ss\r\n    join musicbrainz_recordings mr on mr.spotify_uri = ss.track_uri\r\n    join musicbrainz_recording_tags mrt on mrt.recording_id = mr.musicbrainz_id\r\n    where $__timeFilter(timestamp) and reason_end = 'trackdone' and musicbrainz_genre_id is null\r\n    group by time, metric\r\n    order by time asc, total desc)\r\n  select time, metric, total from metrics where rank <= 5\r\n  union all\r\n  select time, 'Others', sum(total) from metrics where rank > 5\r\n    group by time\r\n    order by time asc;"
    }
   ]
  },
  {
   "title": "Top 10 genres",
   "type": "timeseries",
   "description": "By count of completely streamed tracks.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
   "targets": [
    {
     "rawSql": "with metrics as\r\n  (select $__timeGroup(timestamp, $__interval) as time,\r\n      name as metric,\r\n      count(*) as total,\r\n      dense_rank() over (partition by $__timeGroup(timestamp, $__interval) order by count(*) desc) as rank\r\n    from spotify_streams ss\r\n    join musicbrainz_recordings mr on mr.spotify_uri = ss.track_uri\r\n    join musicbrainz_recording_tags mrt on mrt.recording_id = mr.musicbrainz_id\r\n    where $__timeFilter(timestamp) and reason_end = 'trackdone' and musicbrainz_genre_id is not null\r\n    group by time, metric\r\n    order by time asc, total desc)\r\n  select time, metric, total from metrics where rank <= 5\r\n  union all\r\n  select time, 'Others', sum(total) from metrics where rank > 5\r\n    group by time\r\n    order by time asc;"
    }
   ]
  },
  {
   "title": "Acoustic Properties",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 125 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tracks with various acoustic properties",
     "type": "stat",
     "description": "As a percentage of tracks that have acoustic metadata.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 225 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select \r\n  count(*) filter (where is_danceable) / count(*)::decimal as danceable,\r\n  count(*) filter (where is_acoustic) / count(*)::decimal as acoustic,\r\n  count(*) filter (where is_aggressive) / count(*)::decimal as aggressive,\r\n  count(*) filter (where is_electronic) / count(*)::decimal as electronic,\r\n  count(*) filter (where is_happy) / count(*)::decimal as happy,\r\n  count(*) filter (where is_party) / count(*)::decimal as party,\r\n  count(*) filter (where is_relaxed) / count(*)::decimal as relaxed,\r\n  count(*) filter (where is_sad) / count(*)::decimal as sad,\r\n  count(*) filter (where is_tonal) / count(*)::decimal as tonal,\r\n  count(*) filter (where is_instrumental) / count(*)::decimal as instrumental\r\nfrom spotify_streams ss\r\n  join musicbrainz_recordings mr on mr.spotify_uri = ss.track_uri\r\n  join acousticbrainz a on a.recording_id = mr.musicbrainz_id\r\n  where $__timeFilter(timestamp) and reason_end = 'trackdone'"
      }
     ]
    },
    {
     "title": "Stream and track counts by BPM",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 225 },
     "targets": [
      {
       "rawSql": "select bpm::text, count(*) as \"stream count\", count(distinct track_uri) as \"track count\"\r\nfrom spotify_streams ss\r\n  join musicbrainz_recordings mr on mr.spotify_uri = ss.track_uri\r\n  join acousticbrainz a on a.recording_id = mr.musicbrainz_id\r\n  where $__timeFilter(timestamp) and reason_end = 'trackdone'\r\n  group by bpm\r\n  order by bpm::integer asc"
      }
     ]
    },
    {
     "title": "Key and scale",
     "type": "barchart",
     "description": "Of complete streams of tracks that have acoustic metadata.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 273 },
     "targets": [
      {
       "rawSql": "select key_key || ' ' || key_scale, count(*)\r\n  from spotify_streams ss\r\n  join musicbrainz_recordings mr on mr.spotify_uri = ss.track_uri\r\n  join acousticbrainz a on a.recording_id = mr.musicbrainz_id\r\n  where $__timeFilter(timestamp) and reason_end = 'trackdone'\r\n  group by key_key, key_scale"
      }
     ]
    },
    {
     "title": "Vocal gender",
     "type": "barchart",
     "description": "Of complete streams of tracks that have acoustic metadata.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 273 },
     "targets": [
      {
       "rawSql": "select gender, count(*)\r\n  from spotify_streams ss\r\n  join musicbrainz_recordings mr on mr.spotify_uri = ss.track_uri\r\n  join acousticbrainz a on a.recording_id = mr.musicbrainz_id\r\n  where $__timeFilter(timestamp) and reason_end = 'trackdone'\r\n  group by gender"
      }
     ]
    },
    {
     "title": "Chord key and scale",
     "type": "barchart",
     "description": "Of complete streams of tracks that have acoustic metadata.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 281 },
     "targets": [
      {
       "rawSql": "select chords_key || ' ' || chords_scale, count(*)\r\n  from spotify_streams ss\r\n  join musicbrainz_recordings mr on mr.spotify_uri = ss.track_uri\r\n  join acousticbrainz a on a.recording_id = mr.musicbrainz_id\r\n  where $__timeFilter(timestamp) and reason_end = 'trackdone'\r\n  group by chords_key, chords_scale"
      }
     ]
    },
    {
     "title": "Timbre",
     "type": "barchart",
     "description": "Of complete streams of tracks that have acoustic metadata.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 281 },
     "targets": [
      {
       "rawSql": "select timbre, count(*)\r\n  from spotify_streams ss\r\n  join musicbrainz_recordings mr on mr.spotify_uri = ss.track_uri\r\n  join acousticbrainz a on a.recording_id = mr.musicbrainz_id\r\n  where $__timeFilter(timestamp) and reason_end = 'trackdone'\r\n  group by timbre"
      }
     ]
    }
   ]
  }
 ]
}